// ============================================
// File: internal/downloader/artist_dl.go
package downloader

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/naufalfaisa/amdl/internal/config"
	"github.com/naufalfaisa/amdl/pkg/structs"

	"github.com/AlecAivazis/survey/v2"
	"github.com/fatih/color"
	"github.com/olekukonko/tablewriter"
)

// QualityOption holds information about a downloadable quality
type QualityOption struct {
	ID          string
	Description string
}

// PromptForQualityAfterSelection asks user to select download quality after choosing albums
func PromptForQualityAfterSelection(dlAtmos *bool, dlAAC *bool, aacType *string) error {
	fmt.Println("\n--- Quality Selection ---")

	qualities := []QualityOption{
		{ID: "alac", Description: "Lossless (ALAC)"},
		{ID: "aac", Description: "High-Quality (AAC)"},
		{ID: "atmos", Description: "Dolby Atmos"},
	}

	qualityOptions := make([]string, len(qualities))
	for i, q := range qualities {
		qualityOptions[i] = q.Description
	}

	prompt := &survey.Select{
		Message:  "Select a quality to download for the selected album(s):",
		Options:  qualityOptions,
		PageSize: 5,
	}

	selectedIndex := 0
	err := survey.AskOne(prompt, &selectedIndex)
	if err != nil {
		return err
	}

	selectedQuality := qualities[selectedIndex].ID

	// Reset flags
	*dlAtmos = false
	*dlAAC = false

	// Set the appropriate flag based on selection
	switch selectedQuality {
	case "atmos":
		*dlAtmos = true
		fmt.Println("Quality set to: Dolby Atmos")
	case "aac":
		*dlAAC = true
		*aacType = "aac"
		fmt.Println("Quality set to: High-Quality (AAC)")
	case "alac":
		fmt.Println("Quality set to: Lossless (ALAC)")
	}

	return nil
}

// GetUrlArtistName fetches artist name and ID from artist URL
func GetUrlArtistName(artistUrl string, token string, cfg *config.Config) (string, string, error) {
	storefront, artistId := checkUrlArtist(artistUrl)

	req, err := http.NewRequest("GET", fmt.Sprintf("https://amp-api.music.apple.com/v1/catalog/%s/artists/%s", storefront, artistId), nil)
	if err != nil {
		return "", "", err
	}
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", token))
	req.Header.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36")
	req.Header.Set("Origin", "https://music.apple.com")

	query := url.Values{}
	query.Set("l", cfg.Language)
	req.URL.RawQuery = query.Encode()

	do, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", "", err
	}
	defer do.Body.Close()

	if do.StatusCode != http.StatusOK {
		return "", "", errors.New(do.Status)
	}

	obj := new(structs.AutoGeneratedArtist)
	err = json.NewDecoder(do.Body).Decode(&obj)
	if err != nil {
		return "", "", err
	}

	return obj.Data[0].Attributes.Name, obj.Data[0].ID, nil
}

// CheckArtist fetches and displays artist's albums or music videos, returns selected URLs
// Added quality selection parameters to prompt after album selection
func CheckArtist(artistUrl string, token string, relationship string, cfg *config.Config, artistSelect bool, dlAtmos *bool, dlAAC *bool, aacType *string) ([]string, error) {
	storefront, artistId := checkUrlArtist(artistUrl)
	Num := 0
	var args []string
	var urls []string
	var options [][]string

	for {
		req, err := http.NewRequest("GET", fmt.Sprintf("https://amp-api.music.apple.com/v1/catalog/%s/artists/%s/%s?limit=100&offset=%d&l=%s", storefront, artistId, relationship, Num, cfg.Language), nil)
		if err != nil {
			return nil, err
		}
		req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", token))
		req.Header.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36")
		req.Header.Set("Origin", "https://music.apple.com")

		do, err := http.DefaultClient.Do(req)
		if err != nil {
			return nil, err
		}
		defer do.Body.Close()

		if do.StatusCode != http.StatusOK {
			return nil, errors.New(do.Status)
		}

		obj := new(structs.AutoGeneratedArtist)
		err = json.NewDecoder(do.Body).Decode(&obj)
		if err != nil {
			return nil, err
		}

		for _, album := range obj.Data {
			options = append(options, []string{album.Attributes.Name, album.Attributes.ReleaseDate, album.ID, album.Attributes.URL})
		}

		Num = Num + 100
		if len(obj.Next) == 0 {
			break
		}
	}

	sort.Slice(options, func(i, j int) bool {
		dateI, _ := time.Parse("2006-01-02", options[i][1])
		dateJ, _ := time.Parse("2006-01-02", options[j][1])
		return dateI.Before(dateJ)
	})

	table := tablewriter.NewWriter(os.Stdout)
	switch relationship {
	case "albums":
		table.SetHeader([]string{"", "Album Name", "Date", "Album ID"})
	case "music-videos":
		table.SetHeader([]string{"", "MV Name", "Date", "MV ID"})
	}
	table.SetRowLine(false)
	table.SetHeaderColor(tablewriter.Colors{},
		tablewriter.Colors{tablewriter.FgRedColor, tablewriter.Bold},
		tablewriter.Colors{tablewriter.FgBlackColor, tablewriter.Bold},
		tablewriter.Colors{tablewriter.FgBlackColor, tablewriter.Bold})

	table.SetColumnColor(tablewriter.Colors{tablewriter.FgCyanColor},
		tablewriter.Colors{tablewriter.Bold, tablewriter.FgRedColor},
		tablewriter.Colors{tablewriter.Bold, tablewriter.FgBlackColor},
		tablewriter.Colors{tablewriter.Bold, tablewriter.FgBlackColor})
	for i, v := range options {
		urls = append(urls, v[3])
		options[i] = append([]string{fmt.Sprint(i + 1)}, v[:3]...)
		table.Append(options[i])
	}
	table.Render()

	if artistSelect {
		fmt.Println("You have selected all options:")

		// Prompt for quality before downloading all albums
		if relationship == "albums" {
			err := PromptForQualityAfterSelection(dlAtmos, dlAAC, aacType)
			if err != nil {
				return nil, fmt.Errorf("quality selection cancelled")
			}
		}

		return urls, nil
	}

	reader := bufio.NewReader(os.Stdin)
	fmt.Println("Please select from the " + relationship + " options above (multiple options separated by commas, ranges supported, or type 'all' to select all)")
	cyanColor := color.New(color.FgCyan)
	cyanColor.Print("Enter your choice: ")
	input, _ := reader.ReadString('\n')

	input = strings.TrimSpace(input)
	if input == "all" {
		fmt.Println("You have selected all options:")

		// Prompt for quality before downloading all albums
		if relationship == "albums" {
			err := PromptForQualityAfterSelection(dlAtmos, dlAAC, aacType)
			if err != nil {
				return nil, fmt.Errorf("quality selection cancelled")
			}
		}

		return urls, nil
	}

	selectedOptions := [][]string{}
	parts := strings.Split(input, ",")
	for _, part := range parts {
		if strings.Contains(part, "-") {
			rangeParts := strings.Split(part, "-")
			selectedOptions = append(selectedOptions, rangeParts)
		} else {
			selectedOptions = append(selectedOptions, []string{part})
		}
	}

	fmt.Println("You have selected the following options:")
	for _, opt := range selectedOptions {
		if len(opt) == 1 {
			num, err := strconv.Atoi(opt[0])
			if err != nil {
				fmt.Println("Invalid option:", opt[0])
				continue
			}
			if num > 0 && num <= len(options) {
				fmt.Println(options[num-1])
				args = append(args, urls[num-1])
			} else {
				fmt.Println("Option out of range:", opt[0])
			}
		} else if len(opt) == 2 {
			start, err1 := strconv.Atoi(opt[0])
			end, err2 := strconv.Atoi(opt[1])
			if err1 != nil || err2 != nil {
				fmt.Println("Invalid range:", opt)
				continue
			}
			if start < 1 || end > len(options) || start > end {
				fmt.Println("Range out of range:", opt)
				continue
			}
			for i := start; i <= end; i++ {
				fmt.Println(options[i-1])
				args = append(args, urls[i-1])
			}
		} else {
			fmt.Println("Invalid option:", opt)
		}
	}

	// Prompt for quality after user has selected specific albums
	if len(args) > 0 && relationship == "albums" {
		err := PromptForQualityAfterSelection(dlAtmos, dlAAC, aacType)
		if err != nil {
			return nil, fmt.Errorf("quality selection cancelled")
		}
	}

	return args, nil
}

// checkUrlArtist is a helper function (private)
func checkUrlArtist(url string) (string, string) {
	pat := regexp.MustCompile(`^(?:https:\/\/(?:beta\.music|music|classical\.music)\.apple\.com\/(\w{2})(?:\/artist|\/artist\/.+))\/(?:id)?(\d[^\D]+)(?:$|\?)`)
	matches := pat.FindAllStringSubmatch(url, -1)
	if matches == nil {
		return "", ""
	}
	return matches[0][1], matches[0][2]
}
